# -*- coding: utf-8 -*-
"""embedding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gBH7-vJp_2ab7-xpbg8ywu_XlVAthKex
"""

import random
import json
import pandas as pd
from pathlib import Path
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import TensorDataset, DataLoader
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report
from torch.utils.data import Dataset
from transformers import AutoModel, AutoTokenizer
import json
from tqdm import tqdm

device = "cuda" if torch.cuda.is_available() else "cpu"

class Devign:

    def __init__(self, data_dir:str, seed:int):

        self._seed = seed

        self._df = pd.read_json(data_dir)  # legge il file JSON in un DataFrame pandas

        self._X = self._df['func'].values  # estrae la colonna 'func'
        self._y = self._df['target'].values

        self._X_train, self._X_test, self._y_train, self._y_test = train_test_split(self._X,
                                                                                    self._y,
                                                                                    test_size=0.2,
                                                                                    stratify=self._y,
                                                                                    random_state = self._seed)
    # vari getter
    @property
    def dataframe(self) -> pd.DataFrame:
        return self._df

    @property
    def train_data(self):
        return self._X_train, self._y_train
    @property
    def test_data(self):
        return self._X_test, self._y_test

    @property
    def X(self):
        return self._X

    @property
    def y(self):
        return self._y

# Seed
seed = 42

# Dataset
dataset = Devign(data_dir='/content/data.json', seed = seed)

X = dataset.X
y = dataset.y

checkpoint = "Salesforce/codet5p-110m-embedding"
tokenizer = AutoTokenizer.from_pretrained(checkpoint, trust_remote_code=True)
model = AutoModel.from_pretrained(checkpoint, trust_remote_code=True).to(device)

embedded = []

for func, label in tqdm(zip(X, y)):
    input_ids = tokenizer.encode(func, return_tensors="pt", padding='max_length', truncation=True, max_length=500).to(device)
    embed= model(input_ids)[0]
    embedded.append((embed.tolist(), label))

result = pd.DataFrame(embedded)
result.columns = ['func', 'target']
result.to_json("embedded.json", orient="records")